services:
  db_sqlserver:
    container_name: db_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123"
    networks:
      - my_overlay_network

  app-express:
    container_name: app-express
    # build: 
      # context: ./app
    image: jaimehuacac/img_express:v3
    networks:
      - my_overlay_network
    depends_on:
      - db_sqlserver
    # deploy:
      # replicas: 3

  proxy-inverse:
    build: 
      context: ./proxy
    networks:
      - my_overlay_network
    ports:
      - "8080:80"
    depends_on:
      - app-express

networks:
  my_overlay_network:
    # driver: overlay